# Generated by Django 6.1 on 2026-08-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Name Surname')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('topic', models.CharField(choices=[('general', 'General'), ('bug', 'Error Report'), ('feature', 'Features'), ('support', 'Support')], default='general', max_length=20, verbose_name='Topic')),
                ('message', models.TextField(verbose_name='Message')),
                ('rating', models.IntegerField(choices=[(1, '1 - '), (2, '2 - '), (3, '3 - '), (4, '4 - '), (5, '5 - ')], verbose_name='Evaluaiton')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'ordering': ['created_at'],
            },
        ),
    ]
